image: maven:3-jdk-11

stages:
  - build
  - deploy

build-auth-lib:
  stage: build
  build:
    script: "mvn install -B"

deploy-auth-lib:
  stage: deploy
  deploy:
    script:
      - 'mvn deploy -s ci_settings.xml'
    only:
      - main
