image: maven:3-jdk-11

stages:
  - build
  - deploy

build-auth-lib:
  stage: build
  script:
    - "mvn versions:set -DnewVersion=1.$CI_PIPELINE_IID.$CI_COMMIT_TIMESTAMP"
    - "mvn install -B"

deploy-auth-lib:
  stage: deploy
  script:
    - 'mvn deploy -s ci_settings.xml'
